version: 0.1.{build}

image: Visual Studio 2017

shallow_clone: true

install:
  - choco install -y windows-sdk-10-version-1903-windbg
  - choco install -y --params "Include_symbols=1" python310
  - choco install -y --params "Include_symbols=1" python311
  - choco install -y --params "Include_symbols=1" python312
  - choco install -y --params "Include_symbols=1" python313

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

build:
  project: PyExt.sln

test_script:
  - cd test\scripts
  - py -3 run_all_tests.py %APPVEYOR_BUILD_FOLDER%/%PLATFORM%/%CONFIGURATION%/PyExtTest.exe

# Package up build artifacts.
after_build:
  - 7z a PyExt-%PLATFORM%-%CONFIGURATION%.zip .\*\*\pyext.dll .\*\*\pyext.pdb

artifacts:
  - path: PyExt-$(Platform)-$(Configuration).zip
    name: PyExt-$(Platform)-$(Configuration)

# Deploy build artifacts to GitHub Releases
deploy:
  - provider: GitHub
    release: PyExt-v$(appveyor_build_version)
    description: 'AppVeyor deploy of PyExt v$(appveyor_build_version)'
    auth_token:
      secure: FLeKshd/j9QXbwrM1rCA+tNGkFz8DnN/2Xr/m66oHzv2Qzm9GMb4Bj5UT4GNC5IQ
    artifact: PyExt-$(Platform)-$(Configuration).zip
    draft: true
    prerelease: true
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only